### ISSUE TITLE
Deploy with custom contracts

### ISSUE THREAD

**Issue by tungnnt** [makerdao/dss-deploy-scripts#111]
Hello,
To understand better of system, can I modified some of your contracts, then use this script to deploy my own custom contracts ?
Thanks for your support

**Comment by gbalabasquer** [comment]
Yes, you will have to modify the references in https://github.com/makerdao/dss-deploy-scripts/blob/master/.dapp.json

**Comment by tungnnt** [comment]
> Yes, you will have to modify the references in https://github.com/makerdao/dss-deploy-scripts/blob/master/.dapp.json

Great !
