### ISSUE TITLE
addresses.json should produce checksum addresses

### ISSUE THREAD

**Issue by EdNoepel** [makerdao/dss-deploy-scripts#79]
Checksum addresses have some security benefits.  It'd be nice if contract and token addresses in `addresses.json` used them.

**Comment by DONALDSULLENDER** [comment]
im so confused.

**Comment by EdNoepel** [comment]
This was resolved.  After deployment, an `addresses.json` file is produced enumerating the address for each contract deployed.  It used to produce this file with addresses in all lowercase.  Now it produces the file using [checksum addresses](https://coincodex.com/article/2078/ethereum-address-checksum-explained/).
